import { Game } from "./game.js";

const game = new Game({
  mount: document.getElementById("viewport"),
  rearMirrorFrame: document.getElementById("rearview-mirror"),
  cockpitFrame: document.getElementById("cockpit-frame"),
  hudElements: {
    distance: document.getElementById("distance-value"),
    lane: document.getElementById("lane-value"),
    nos: document.getElementById("nos-value"),
    coins: document.getElementById("coins-value"),
    pursuit: document.getElementById("pursuit-value"),
    race: document.getElementById("race-value"),
    assist: document.getElementById("assist-value"),
    overlay: document.getElementById("crash-overlay"),
    crashMessage: document.getElementById("crash-message"),
    scoreStatus: document.getElementById("score-status"),
    restartButton: document.getElementById("restart-button"),
    menuButton: document.getElementById("menu-button"),
    menuOverlay: document.getElementById("menu-overlay"),
    accessibilityOverlay: document.getElementById("accessibility-overlay"),
    accessibilityNamePanel: document.getElementById("accessibility-name-panel"),
    accessibilityQuestionPanel: document.getElementById("accessibility-question-panel"),
    accessibilitySetupPanel: document.getElementById("accessibility-setup-panel"),
    onboardingNameInput: document.getElementById("onboarding-name-input"),
    accessibilityNameContinueButton: document.getElementById("accessibility-name-continue-button"),
    accessibilityYesButton: document.getElementById("accessibility-yes-button"),
    accessibilityNoButton: document.getElementById("accessibility-no-button"),
    accessibilityContinueButton: document.getElementById("accessibility-continue-button"),
    accessibilityContrastButton: document.getElementById("accessibility-contrast-button"),
    accessibilityColorButton: document.getElementById("accessibility-color-button"),
    menuPlayButton: document.getElementById("menu-play-button"),
    menuNewRunButton: document.getElementById("menu-new-run-button"),
    playerNameInput: document.getElementById("player-name-input"),
    leaderboardList: document.getElementById("leaderboard-list"),
    menuStatus: document.getElementById("menu-status"),
    accessibilityReviewButton: document.getElementById("accessibility-review-button"),
    accessibilityStatus: document.getElementById("accessibility-status"),
    highContrastButton: document.getElementById("high-contrast-button"),
    colorAssistButton: document.getElementById("color-assist-button"),
    aiToggleButton: document.getElementById("ai-toggle-button"),
    secretPanel: document.getElementById("secret-menu-panel"),
    secretTrigger: document.getElementById("secret-menu-trigger"),
    menuSoloTab: document.getElementById("menu-solo-tab"),
    menuMultiplayerTab: document.getElementById("menu-multiplayer-tab"),
    menuOptionsTab: document.getElementById("menu-options-tab"),
    soloMenuPanel: document.getElementById("solo-menu-panel"),
    multiplayerMenuPanel: document.getElementById("multiplayer-menu-panel"),
    optionsMenuPanel: document.getElementById("options-menu-panel"),
    multiplayerStatus: document.getElementById("multiplayer-status"),
    lobbyCodeInput: document.getElementById("lobby-code-input"),
    multiplayerLobbyCard: document.getElementById("multiplayer-lobby-card"),
    multiplayerLobbyCode: document.getElementById("multiplayer-lobby-code"),
    multiplayerPlayerList: document.getElementById("multiplayer-player-list"),
    multiplayerCreateButton: document.getElementById("multiplayer-create-button"),
    multiplayerJoinButton: document.getElementById("multiplayer-join-button"),
    multiplayerReadyButton: document.getElementById("multiplayer-ready-button"),
    multiplayerStartButton: document.getElementById("multiplayer-start-button"),
    multiplayerLeaveButton: document.getElementById("multiplayer-leave-button"),
    leftIndicator: document.getElementById("turn-indicator-left"),
    rightIndicator: document.getElementById("turn-indicator-right"),
    menuTrigger: document.getElementById("menu-trigger"),
    fullscreenToggle: document.getElementById("fullscreen-toggle"),
    controlsPanel: document.getElementById("controls-panel"),
    graphicsPresetSelect: document.getElementById("graphics-preset-select"),
    graphicsPresetStatus: document.getElementById("graphics-preset-status"),
    vibrationToggleButton: document.getElementById("vibration-toggle-button"),
    trackingConsent: document.getElementById("tracking-consent"),
    trackingStatus: document.getElementById("tracking-status"),
    trackingAcceptButton: document.getElementById("tracking-accept-button"),
    trackingDeclineButton: document.getElementById("tracking-decline-button"),
  },
});

game.start();
